In [1]:
import numpy as np
import pandas as pd
import math
import sys
import datetime as dt

In [2]:
# quarterly recipe data
data = pd.read_csv("../data/split data/2-SP500 Fundamental.csv") 
data_tmp = pd.DataFrame(data)
print(data_tmp.head())
print(data_tmp.tail())
print(data_tmp.shape[0])

   gvkey  datadate  fyearq  fqtr   tic                        conm datacqtr  \
0   1013  19900131    1990     1  ADCT  ADC TELECOMMUNICATIONS INC   1989Q4
1   1013  19900430    1990     2  ADCT  ADC TELECOMMUNICATIONS INC   1990Q1
2   1013  19900731    1990     3  ADCT  ADC TELECOMMUNICATIONS INC   1990Q2
3   1013  19901031    1990     4  ADCT  ADC TELECOMMUNICATIONS INC   1990Q3
4   1013  19910131    1991     1  ADCT  ADC TELECOMMUNICATIONS INC   1990Q4

  datafqtr         rdq     actq   ...     oiadpq   revtq   saleq  teqq  \
0   1990Q1  19900223.0   85.600   ...      9.531  62.043  62.043   NaN
1   1990Q2  19900529.0   87.438   ...      7.588  60.195  60.195   NaN
2   1990Q3  19900829.0   89.083   ...      9.577  65.814  65.814   NaN
3   1990Q4  19901213.0  102.525   ...     11.049  71.750  71.750   NaN
4   1991Q1  19910221.0  107.228   ...     11.012  72.902  72.902   NaN

    wcapq   xoprq  costat  mkvaltq   prccq  gsector
0  58.483  49.240       I      NaN  17.500     45.0
1  62.565  49.377       I      NaN  21.250     45.0
2  58.124  52.135       I      NaN  20.000     45.0
3  65.190  56.999       I      NaN  16.375     45.0
4  70.514  57.943       I      NaN  26.250     45.0

[5 rows x 36 columns]
        gvkey  datadate  fyearq  fqtr   tic          conm datacqtr datafqtr  \
91211  316056  20160930    2016     3  ALLE  ALLEGION PLC   2016Q3   2016Q3
91212  316056  20161231    2016     4  ALLE  ALLEGION PLC   2016Q4   2016Q4
91213  316056  20170331    2017     1  ALLE  ALLEGION PLC   2017Q1   2017Q1
91214  316056  20170630    2017     2  ALLE  ALLEGION PLC   2017Q2   2017Q2
91215  316056  20170930    2017     3  ALLE  ALLEGION PLC   2017Q3   2017Q3

              rdq   actq   ...     oiadpq  revtq  saleq   teqq  wcapq  xoprq  \
91211  20161027.0  802.3   ...      121.9  581.1  581.1  155.5  370.0  442.0
91212  20170209.0  829.3   ...       99.5  569.7  569.7  116.4  399.7  454.0
91213  20170427.0  742.2   ...       99.6  548.8  548.8  155.0  343.7  432.7
91214  20170727.0  839.2   ...      134.4  627.0  627.0  269.4  402.4  476.4
91215  20171026.0  924.6   ...      133.5  609.3  609.3  372.1  492.4  458.6

       costat    mkvaltq  prccq  gsector
91211       A  6615.3600  68.91     20.0
91212       A  6097.5360  64.00     20.0
91213       A  7211.1820  75.70     20.0
91214       A  7704.7776  81.12     20.0
91215       A  8216.8982  86.47     20.0

[5 rows x 36 columns]
91216

In [3]:
# stock name
stock_name = list(set(data_tmp['tic']))
for i in range(len(stock_name)-1):
    if(type(stock_name[i]) != str):
        del stock_name[i]  # delete nan in the list

"""
# transfer index into date
date = list(data_tmp['datadate'])
a = date
for i in range(len(date)):
    b = dt.strptime(str(date[i]), '%Y%m%d')
    a[i] = b.strftime('%Y-%m-%d')
series = data_tmp
series.index = a
print(series.head())
"""
print(data_tmp.columns.values)

['gvkey' 'datadate' 'fyearq' 'fqtr' 'tic' 'conm' 'datacqtr' 'datafqtr'
 'rdq' 'actq' 'apq' 'atq' 'ceqq' 'chq' 'cogsq' 'cshoq' 'dlcq' 'dlttq' 'dpq'
 'epspxq' 'invfgq' 'lctq' 'lltq' 'lseq' 'msaq' 'niq' 'oiadpq' 'revtq'
 'saleq' 'teqq' 'wcapq' 'xoprq' 'costat' 'mkvaltq' 'prccq' 'gsector']

In [4]:
# daily close price
data_fd = pd.read_csv("../data/split data/1-SP500 Price 1990 to 1999.csv", low_memory = False) # first decade
data_sd = pd.read_csv("../data/split data/1-SP500 Price 2000 to 2009.csv", low_memory = False) # second decade
data_td = pd.read_csv("../data/split data/1-SP500 Price 2010 to 2017.csv", low_memory = False) # third decade

data_fd = pd.DataFrame(data_fd[list(['datadate', 'tic', 'prccd', 'gsector'])])
data_sd = pd.DataFrame(data_sd[list(['datadate', 'tic', 'prccd', 'gsector'])])
data_td = pd.DataFrame(data_td[list(['datadate', 'tic', 'prccd', 'gsector'])])

print(data_fd.shape[0] + data_sd.shape[0] + data_td.shape[0])

data_daily = [data_fd, data_sd, data_td]
data_daily = pd.concat(data_daily)

print(data_daily.shape[0])


stock_name_daily = list(set(data_daily['tic']))
for i in range(len(stock_name_daily)-1):
    if(type(stock_name_daily[i]) != str):
        del stock_name_daily[i]  # delete nan in the list

6426271
6426271

In [5]:
len(stock_name_daily)

1825

In [9]:
# use trade date instead of report quarterly date
times = list(data_tmp['datadate']) # quarterly report date
for i in range(len(times)):
    quarter = (times[i] - int(times[i]/10000)*10000) + 200
    if 1201 < quarter:
        times[i] = int(times[i]/10000 + 1)*10000 + 301
    if quarter <= 301:
        times[i] = int(times[i]/10000)*10000 + 301
    if 301 < quarter <= 601:
        times[i] = int(times[i]/10000)*10000 + 601
    if 601 < quarter <= 901:
        times[i] = int(times[i]/10000)*10000 + 901
    if 901 < quarter <= 1201:
        times[i] = int(times[i]/10000 + 1)*10000 + 1201
    time_tmp = times[i]
    year = int(time_tmp/10000)
    month = int((time_tmp - year*10000)/100)
    day = int(time_tmp - year*10000 - month*100)
    if(time_tmp < 20171120):
        while(dt.date(year, month, day).weekday() > 4):
            time_tmp = time_tmp + 1
            year = int(time_tmp/10000)
            month = int((time_tmp - year*10000)/100)
            day = int(time_tmp - year*10000 - month*100)
        times[i] = time_tmp

data_factor = pd.DataFrame({'datadate': times, 'tic': data_tmp['tic'], 'gsector':data_tmp['gsector'], 
                            'epspxq': data_tmp['epspxq']})
print(data_factor.head(16))
print(data_factor.tail(16))

    datadate  epspxq  gsector   tic
0   19900601    0.44     45.0  ADCT
1   19900903    0.36     45.0  ADCT
2   19911202    0.44     45.0  ADCT
3   19910301    0.49     45.0  ADCT
4   19910603    0.50     45.0  ADCT
5   19910902    0.49     45.0  ADCT
6   19921201    0.32     45.0  ADCT
7   19920302    0.34     45.0  ADCT
8   19920601   -0.09     45.0  ADCT
9   19920901    0.46     45.0  ADCT
10  19931201    0.56     45.0  ADCT
11  19930301    0.62     45.0  ADCT
12  19930601    0.39     45.0  ADCT
13  19930901    0.51     45.0  ADCT
14  19941201    0.33     45.0  ADCT
15  19940301    0.37     45.0  ADCT
       datadate  epspxq  gsector   tic
91200  20140303    0.12     20.0  ALLE
91201  20140602    0.38     20.0  ALLE
91202  20140901    0.53     20.0  ALLE
91203  20151201    0.66     20.0  ALLE
91204  20150302    0.37     20.0  ALLE
91205  20150601    0.48     20.0  ALLE
91206  20150901    0.67     20.0  ALLE
91207  20161201   -0.28     20.0  ALLE
91208  20160301    0.75     20.0  ALLE
91209  20160601    0.60     20.0  ALLE
91210  20160901    0.99     20.0  ALLE
91211  20171201    0.02     20.0  ALLE
91212  20170301    0.77     20.0  ALLE
91213  20170601    0.72     20.0  ALLE
91214  20170901    1.11     20.0  ALLE
91215  20181201    0.95     20.0  ALLE

In [10]:
data_factor['prccd'] = [0]*data_factor.shape[0]
for i in stock_name:
    if (i in stock_name_daily):
        ind_quarter = np.where(data_factor['tic'] == i)[0]
        date_price_daily = data_daily.loc[data_daily['tic'] == i, list(['datadate', 'prccd'])]
        date_price_daily.index = range(date_price_daily.shape[0])
        date_max = max(date_price_daily['datadate'])
        date_min = min(date_price_daily['datadate'])
        for j in ind_quarter:
            if (data_factor.loc[j, 'datadate'] < date_min or data_factor.loc[j, 'datadate'] > date_max):
                data_factor.loc[j, 'prccd'] = np.nan
            else:
                if(data_factor.loc[j, 'datadate'] in set(date_price_daily['datadate'])):
                    ind_tmp = np.where(date_price_daily['datadate'] == data_factor.loc[j, 'datadate'])[0]
                    data_factor.loc[j, 'prccd'] = date_price_daily.loc[ind_tmp, 'prccd'].values
                else:
                    data_factor.loc[j, 'prccd'] = np.nan

In [11]:
print(data_factor)
writer = pd.ExcelWriter('trade date and price.xlsx')
data_factor.to_excel(writer,'Sheet1')
writer.save()

       datadate  epspxq  gsector   tic   prccd
0      19900601    0.44     45.0  ADCT  22.000
1      19900903    0.36     45.0  ADCT     NaN
2      19911202    0.44     45.0  ADCT  25.125
3      19910301    0.49     45.0  ADCT  32.000
4      19910603    0.50     45.0  ADCT  40.750
5      19910902    0.49     45.0  ADCT     NaN
6      19921201    0.32     45.0  ADCT  45.500
7      19920302    0.34     45.0  ADCT  25.750
8      19920601   -0.09     45.0  ADCT  35.000
9      19920901    0.46     45.0  ADCT  36.000
10     19931201    0.56     45.0  ADCT  35.375
11     19930301    0.62     45.0  ADCT  42.000
12     19930601    0.39     45.0  ADCT  54.750
13     19930901    0.51     45.0  ADCT  36.000
14     19941201    0.33     45.0  ADCT  41.000
15     19940301    0.37     45.0  ADCT  36.875
16     19940601    0.24     45.0  ADCT  41.375
17     19940901    0.36     45.0  ADCT  46.000
18     19951201    0.40     45.0  ADCT  43.125
19     19950301    0.46     45.0  ADCT  29.500
20     19950601    0.38     45.0  ADCT  30.250
21     19950901    0.18     45.0  ADCT  41.750
22     19961202    0.26     45.0  ADCT  37.750
23     19960301    0.30     45.0  ADCT  39.250
24     19960603    0.26     45.0  ADCT  46.500
25     19960902    0.31     45.0  ADCT     NaN
26     19971201    0.36     45.0  ADCT  36.688
27     19970303    0.44     45.0  ADCT  27.750
28     19970602    0.08     45.0  ADCT  33.125
29     19970901    0.22     45.0  ADCT     NaN
...         ...     ...      ...   ...     ...
91186  20170601    2.00     15.0   LYB  80.550
91187  20170901    2.83     15.0   LYB  90.250
91188  20181201    2.67     15.0   LYB     NaN
91189  20110601     NaN     20.0  ALLE     NaN
91190  20110901     NaN     20.0  ALLE     NaN
91191  20121203     NaN     20.0  ALLE     NaN
91192  20120301    2.23     20.0  ALLE     NaN
91193  20120601    0.46     20.0  ALLE     NaN
91194  20120903    0.57     20.0  ALLE     NaN
91195  20131202    0.57     20.0  ALLE  43.140
91196  20130301    0.59     20.0  ALLE     NaN
91197  20130603    0.40     20.0  ALLE     NaN
91198  20130902    0.60     20.0  ALLE     NaN
91199  20141201   -0.79     20.0  ALLE  53.700
91200  20140303    0.12     20.0  ALLE  53.490
91201  20140602    0.38     20.0  ALLE  52.070
91202  20140901    0.53     20.0  ALLE     NaN
91203  20151201    0.66     20.0  ALLE  68.030
91204  20150302    0.37     20.0  ALLE  58.820
91205  20150601    0.48     20.0  ALLE  62.040
91206  20150901    0.67     20.0  ALLE  58.560
91207  20161201   -0.28     20.0  ALLE  65.460
91208  20160301    0.75     20.0  ALLE  64.830
91209  20160601    0.60     20.0  ALLE  68.190
91210  20160901    0.99     20.0  ALLE  71.840
91211  20171201    0.02     20.0  ALLE     NaN
91212  20170301    0.77     20.0  ALLE  73.690
91213  20170601    0.72     20.0  ALLE  79.140
91214  20170901    1.11     20.0  ALLE  79.150
91215  20181201    0.95     20.0  ALLE     NaN

[91216 rows x 5 columns]

In [12]:
# factors calculation function
def revenue_growth(df):
    # REVTQ (T) / REVTQ (T-1) -1
    rev = df['revtq']
    rev = round(rev.shift(1)/rev - 1, 3)
    return rev

def price_to_cash_flow_ratio(df2, df):
    # Adjusted Close Price * CSHOQ 
    # / [(NIQ (Net Income (Loss)) + DPQ (Depreciation and Amortization, Total) – (WCAPQ (T)- WCAPQ (T-1))]
    tmp = df['wcapq']
    tmp = round(tmp.shift(1) - tmp, 3)
    ptcfr = round(df2['prccd']*df['cshoq']/(df['niq'] + df['dpq'] - tmp), 3)
    return ptcfr
    
    
def cash_ratio(df):
    # [CHQ (Cash) + MSAQ (Marketable Security Adjustments)] / LCTQ (Current Liabilities, Total)
    chq_ratio = round((df['chq'] + df['msaq'])/df['lctq'], 3)
    return chq_ratio

def ev(df2 ,df):
    # EV = PRCCQ (Price Close, Quarter) * CSHOQ (Common Shares Outstanding) + DLTTQ (Long-Term Debt, Total) 
    # + DLCQ (Debt in Current Liabilities) - CHQ (Cash)
    ev = round(df2['prccd'] * df['cshoq'] + df['mkvaltq'] + df['dlttq'] + df['dlcq'] - df['chq'], 3)
    return ev

def ebitda(df):
    
    # EBITDA = REVTQ (Revenue, Total) – XOPRQ (Operating Expense, Total) 
    # + DPQ (Depreciation and Amortization, Total)
    ebitda = round(df['revtq'] - df['xoprq'] + df['dpq'], 3)
    return ebitda

def ev_to_cfo(df2, df):
    # [PRCCQ (Price Close, Quarter) * CSHOQ + DLTTQ (Long-Term Debt, Total) + DLCQ (Debt in Current Liabilities) - CHQ (Cash)]
    # /[(NIQ (Net Income (Loss)) + DPQ (Depreciation and Amortization, Total) – (WCAPQ (T)- WCAPQ (T-1))]
    tmp = df['wcapq']
    tmp = tmp.shift(1) - tmp
    
    #num = df['mkvaltq'] + df['dlttq'] + df['dlcq'] - df['chq']
    num2 = df['niq'] + df['dpq'] - tmp
    evtocfo = round(ev(df2, df)/num2, 3)
    return evtocfo

def roa(df):
    # NIQ (Net Income (Loss)) / ATQ (Assets, Total)
    return round(df['niq']/df['atq'], 3)

def roe(df):
    # NIQ (Net Income (Loss)) / CEQQ (Common/Ordinary Equity, Total)
    return round(df['niq']/df['ceqq'], 3)

def pe(df2, df):
    # Current market close price / EPSPXQ (Earnings Per Share (Basic) - Excluding Extraordinary Items)
    return round(df2['prccd']/df['epspxq'], 3)

def ps(df2, df):
    # Current market close price / [REVTQ (Revenue, Total) / CSHOQ (Common Shares Outstanding)]
    return round(df2['prccd'] / df['revtq'] / df['cshoq'], 3)

def net_profit_margin(df):
    # NIQ (Net Income (Loss)) / REVTQ (Revenue, Total)
    return round(df['niq']/df['revtq'], 3)

def gross_profit_margin(df):
    # [REVTQ (Revenue, Total) – COGSQ (Cost of Goods Sold)] / REVTQ (Revenue, Total)
    return round((df['revtq'] - df['cogsq'])/df['revtq'], 3)

def operating_margin(df):
    # OIADPQ (Operating Income After Depreciation, Quarterly) / SALEQ (Sales/Turnover (Net))
    return round(df['oiadpq']/df['saleq'], 3)

def price_to_book(df2, df):
    # Current market close price / {[ATQ (Assets, Total) – LTQ(Liabilities, Total)] / CSHOQ}
    #return round(df2['prccd'] / ((df['atq'] - df['ltq'])/df['cshoq']), 3)
    return round(df2['prccd'] / ((df['atq'] - df['lltq'])/df['cshoq']), 3)

def long_term_debt_to_total_asset(df):
    # DLTTQ (Long-Term Debt, Total) / ATQ (Assets, Total)
    return round(df['dlttq'] / df['atq'], 3)

def working_capital_ratio(df):
    # ACTQ (Current Assets, Total) / LCTQ (Current Liabilities, Total)
    return round(df['actq'] / df['lctq'], 3)

def debt_equity(df):
    # LTQ (Liabilities, Total) / CEQQ (Common/Ordinary Equity, Total)
    #return round(df['ltq']/df['ceqq'], 3)
    return round(df['lltq']/df['ceqq'], 3)


def quick_ratio(df):
    # [ ACTQ (Current Assets, Total) - INVTQ (Inventory, Finished Goods) ] / LCTQ (Current Liabilities, Total)
    #return round((df['actq'] - df['invtq']) / df['lctq'], 3)
    return round((df['actq'] - df['invfgq']) / df['lctq'], 3)

def days_sales_of_inventory(df):
    # INVTQ (Inventory, Finished Goods) / COGSQ (Cost of Goods Sold) * 365
    #return round(df['invtq'] / df['cogsq'] * 365, 3)
    return round(df['invfgq'] / df['cogsq'] * 365, 3)

def days_payable_outstanding(df):
    # APQ (Account Payable/Creditors, Trade) / COGSQ (Cost of Goods Sold) * 365
    return round(df['apq'] / df['cogsq'] * 365, 3)

In [ ]:
# factors calculation
pd.set_option('mode.chained_assignment', None)
data_factor_store = pd.DataFrame(columns = ['datadate', 'gsector', 'tic', 'prccd',
                                            'revenue_growth', 'price_to_cash_flow_ratio', 
                                            'cash_ratio', 'ebitda', 'ev_to_cfo', 'epspxq', 
                                            'roa', 'roe', 'pe', 'ps', 'net_profit_margin', 
                                            'gross_profit_margin', 'operating_margin', 
                                            'price_to_book', 'long_term_debt_to_total_asset', 
                                            'working_capital_ratio', 'debt_equity', 'quick_ratio', 
                                            'days_sales_of_inventory', 'days_payable_outstanding'])
for i in stock_name:
    df = data_tmp.loc[data_tmp['tic'] == i, ]
    df2 = data_factor.loc[data_factor['tic'] == i, ]
    df2.loc[:, 'revenue_growth'] = list(revenue_growth(df))
    df2.loc[:, 'price_to_cash_flow_ratio'] = list(price_to_cash_flow_ratio(df2, df))
    df2.loc[:, 'cash_ratio'] = list(cash_ratio(df))
    df2.loc[:, 'ebitda'] = list(ebitda(df))
    df2.loc[:, 'ev_to_cfo'] = list(ev_to_cfo(df2, df))
    df2.loc[:, 'roa'] = list(roa(df))
    df2.loc[:, 'roe'] = list(roe(df))
    df2.loc[:, 'pe'] = list(pe(df2, df))
    df2.loc[:, 'ps'] = list(ps(df2, df))
    df2.loc[:, 'net_profit_margin'] = list(net_profit_margin(df))
    df2.loc[:, 'gross_profit_margin'] = list(gross_profit_margin(df))
    df2.loc[:, 'operating_margin'] = list(operating_margin(df))
    df2.loc[:, 'price_to_book'] = list(price_to_book(df2, df))
    df2.loc[:, 'long_term_debt_to_total_asset'] = list(long_term_debt_to_total_asset(df))
    df2.loc[:, 'working_capital_ratio'] = list(working_capital_ratio(df))
    df2.loc[:, 'debt_equity'] = list(debt_equity(df))
    df2.loc[:, 'quick_ratio'] = list(quick_ratio(df))
    df2.loc[:, 'days_sales_of_inventory'] = list(days_sales_of_inventory(df))
    df2.loc[:, 'days_payable_outstanding'] = list(days_payable_outstanding(df))
    data_factor_store = [data_factor_store, df2]
    data_factor_store = pd.concat(data_factor_store)

In [ ]:
data_factor = data_factor_store
print(data_factor)
writer = pd.ExcelWriter('factor matrix with tradable date.xlsx')
data_factor.to_excel(writer,'Sheet1')
writer.save()

       cash_ratio  datadate  days_payable_outstanding  \
36102         NaN  19900601                   127.834
36103         NaN  19900903                   345.391
36104         NaN  19911202                   651.688
36105         NaN  19910301                   272.553
36106         NaN  19910603                   128.343
36107         NaN  19910902                   388.439
36108         NaN  19921201                   640.033
36109         NaN  19920302                   272.957
36110         NaN  19920601                   149.177
36111         NaN  19920901                   358.967
36112         NaN  19931201                   621.971
36113         NaN  19930301                   181.075
36114         NaN  19930601                   110.944
36115         NaN  19930901                   283.228
36116         NaN  19941201                   548.822
36117         NaN  19940301                   188.170
36118         NaN  19940601                   103.768
36119         NaN  19940901                   337.796
36120         NaN  19951201                   639.970
36121         NaN  19950301                   309.537
36122         NaN  19950601                   141.986
36123         NaN  19950901                   427.404
36124         NaN  19961202                   754.607
36125         NaN  19960301                   304.809
36126         NaN  19960603                   201.474
36127         NaN  19960902                   336.155
36128         NaN  19971201                   510.697
36129         NaN  19970303                   248.164
36130         NaN  19970602                    93.064
36131         NaN  19970901                   400.364
...           ...       ...                       ...
16105       0.102  20100901                   207.236
16106       0.139  20111201                   190.744
16107       0.050  20110301                   209.838
16108         NaN  20110601                   162.237
16109         NaN  20110901                   178.533
16110         NaN  20121203                   165.684
16111       0.050  20120301                   198.111
16112       0.068  20120601                   154.703
16113       0.066  20120903                   159.232
16114       0.063  20131202                   181.080
16115       0.074  20130301                   202.343
16116       0.059  20130603                   151.024
16117       0.076  20130902                   155.841
16118       0.106  20141201                   171.148
16119       0.113  20140303                   205.060
16120       0.113  20140602                   165.357
16121       0.132  20140901                   170.493
16122       0.097  20151201                   178.707
16123       0.120  20150302                   191.133
16124       0.102  20150601                   174.293
16125       0.117  20150901                   193.289
16126       0.103  20161201                   172.354
16127       0.137  20160301                   175.956
16128       0.098  20160601                   145.047
16129       0.126  20160901                   148.163
16130       0.089  20171201                   161.619
16131       0.102  20170301                   204.367
16132       0.138  20170601                   147.631
16133       0.094  20170901                   164.191
16134       0.105  20181201                   184.943

       days_sales_of_inventory  debt_equity  ebitda  epspxq  ev_to_cfo  \
36102                      NaN          NaN   149.8    1.49        NaN
36103                      NaN          NaN    78.6    0.69        NaN
36104                      NaN          NaN    56.9    0.34        NaN
36105                      NaN          NaN   132.4    1.34        NaN
36106                      NaN          NaN   161.4    1.62        NaN
36107                      NaN          NaN    72.7    0.52        NaN
36108                      NaN          NaN    55.3    0.28        NaN
36109                      NaN          NaN   135.5    1.29        NaN
36110                      NaN          NaN   139.2    1.36        NaN
36111                      NaN          NaN    68.3    0.56        NaN
36112                      NaN          NaN    47.3    0.32        NaN
36113                      NaN          NaN   122.9    1.12        NaN
36114                      NaN          NaN   153.3    1.66        NaN
36115                      NaN          NaN    67.8    0.29        NaN
36116                      NaN          NaN    46.1    0.16        NaN
36117                      NaN          NaN   123.9    0.68        NaN
36118                      NaN          NaN   166.2    0.95        NaN
36119                      NaN          NaN    66.8    0.30        NaN
36120                      NaN          NaN    44.6    0.14        NaN
36121                      NaN          NaN   122.3    0.67        NaN
36122                      NaN          NaN   163.5    0.80        NaN
36123                      NaN          NaN    72.5    0.34        NaN
36124                      NaN          NaN    47.2    0.12        NaN
36125                      NaN          NaN   130.2    0.71        NaN
36126                      NaN          NaN   180.9    0.90        NaN
36127                      NaN          NaN    94.6    0.50        NaN
36128                      NaN          NaN    68.3    0.30        NaN
36129                      NaN          NaN   139.9    0.71        NaN
36130                      NaN          NaN   177.6    0.82        NaN
36131                      NaN          NaN    98.6    0.59        NaN
...                        ...          ...     ...     ...        ...
16105                      NaN          NaN  1330.0    2.98     20.243
16106                      NaN          NaN  1645.0    0.98     59.573
16107                      NaN          NaN  1290.0    0.53    -78.090
16108                      NaN          NaN  1568.0    0.86     45.901
16109                      NaN          NaN  1243.0    0.60   -189.165
16110                      NaN          NaN  1506.0    0.68     78.207
16111                      NaN          NaN  1109.0    0.35    -97.160
16112                      NaN          NaN  1464.0    0.88    118.836
16113                      NaN          NaN  1178.0    0.51        NaN
16114                      NaN          NaN  1566.0    0.45    128.645
16115                      NaN          NaN  1339.0    0.65    -77.097
16116                      NaN          NaN  1524.0    0.86     54.676
16117                      NaN          NaN  1154.0    0.47        NaN
16118                      NaN          NaN  1651.0    1.02     86.821
16119                      NaN          NaN  1405.0    0.74    108.700
16120                      NaN          NaN  1415.0    0.65    120.900
16121                      NaN          NaN  1297.0    0.27        NaN
16122                      NaN          NaN  1672.0    0.91    241.630
16123                      NaN          NaN  1447.0    0.42    100.234
16124                      NaN          NaN  1773.0    0.91   -216.140
16125                      NaN          NaN  1496.0    0.70     74.310
16126                      NaN          NaN  1833.0    1.00    184.322
16127                      NaN          NaN  1408.0    0.60   -186.713
16128                      NaN          NaN  1586.0    0.88    116.760
16129                      NaN          NaN  1508.0    0.73     82.146
16130                      NaN          NaN  1985.0    1.10        NaN
16131                      NaN          NaN  1747.0    0.73     57.756
16132                      NaN          NaN  2063.0    1.01     96.121
16133                      NaN          NaN  1735.0    0.62   -114.191
16134                      NaN          NaN  2170.0    1.03        NaN

       gross_profit_margin  gsector          ...             prccd  \
36102                0.178     55.0          ...            39.875
36103                0.212     55.0          ...               NaN
36104                0.227     55.0          ...            44.750
36105                0.210     55.0          ...            41.250
36106                0.188     55.0          ...            41.750
36107                0.218     55.0          ...               NaN
36108                0.214     55.0          ...            48.000
36109                0.212     55.0          ...            42.500
36110                0.185     55.0          ...            43.000
36111                0.208     55.0          ...            47.000
36112                0.204     55.0          ...            27.625
36113                0.164     55.0          ...            54.625
36114                0.173     55.0          ...            28.500
36115                0.183     55.0          ...            29.250
36116                0.181     55.0          ...            22.625
36117                0.174     55.0          ...            26.875
36118                0.161     55.0          ...            26.750
36119                0.182     55.0          ...            24.375
36120                0.189     55.0          ...            25.250
36121                0.230     55.0          ...            24.500
36122                0.195     55.0          ...            26.125
36123                0.216     55.0          ...            26.250
36124                0.207     55.0          ...            36.375
36125                0.208     55.0          ...            27.750
36126                0.188     55.0          ...            27.500
36127                0.218     55.0          ...               NaN
36128                0.235     55.0          ...            40.500
36129                0.172     55.0          ...            33.375
36130                0.139     55.0          ...            34.375
36131                0.249     55.0          ...               NaN
...                    ...      ...          ...               ...
16105                0.320     55.0          ...            43.860
16106                0.350     55.0          ...            51.350
16107                0.275     55.0          ...            45.570
16108                0.328     55.0          ...            47.120
16109                0.300     55.0          ...            48.590
16110                0.331     55.0          ...            50.750
16111                0.264     55.0          ...            50.410
16112                0.351     55.0          ...            51.630
16113                0.300     55.0          ...               NaN
16114                0.383     55.0          ...            64.310
16115                0.339     55.0          ...            56.420
16116                0.348     55.0          ...            55.550
16117                0.286     55.0          ...               NaN
16118                0.391     55.0          ...            72.280
16119                0.347     55.0          ...            68.590
16120                0.305     55.0          ...            69.600
16121                0.352     55.0          ...               NaN
16122                0.432     55.0          ...            67.410
16123                0.382     55.0          ...            70.320
16124                0.419     55.0          ...            70.500
16125                0.421     55.0          ...            67.800
16126                0.497     55.0          ...            72.750
16127                0.411     55.0          ...            69.950
16128                0.423     55.0          ...            71.680
16129                0.441     55.0          ...            74.060
16130                0.506     55.0          ...               NaN
16131                0.421     55.0          ...            76.250
16132                0.471     55.0          ...            81.410
16133                0.451     55.0          ...            78.330
16134                0.530     55.0          ...               NaN

       price_to_book  price_to_cash_flow_ratio     ps  quick_ratio  \
36102            NaN                       NaN  0.002          NaN
36103            NaN                       NaN    NaN          NaN
36104            NaN                    37.903  0.009          NaN
36105            NaN                    12.711  0.003          NaN
36106            NaN                    11.209  0.002          NaN
36107            NaN                       NaN    NaN          NaN
36108            NaN                    35.945  0.010          NaN
36109            NaN                    33.823  0.003          NaN
36110            NaN                   751.533  0.003          NaN
36111            NaN                    59.156  0.007          NaN
36112            NaN                   170.765  0.006          NaN
36113            NaN                    15.417  0.003          NaN
36114            NaN                     4.480  0.002          NaN
36115            NaN                    13.335  0.002          NaN
36116            NaN                   -19.400  0.002          NaN
36117            NaN                    22.659  0.001          NaN
36118            NaN                    12.247  0.001          NaN
36119            NaN                   -59.431  0.002          NaN
36120            NaN                   -47.935  0.003          NaN
36121            NaN                    32.545  0.001          NaN
36122            NaN                    16.214  0.001          NaN
36123            NaN                   441.578  0.002          NaN
36124            NaN                   -38.614  0.005          NaN
36125            NaN                    11.565  0.001          NaN
36126            NaN                    11.706  0.001          NaN
36127            NaN                       NaN    NaN          NaN
36128            NaN                    24.875  0.004          NaN
36129            NaN                    21.452  0.001          NaN
36130            NaN                    15.745  0.001          NaN
36131            NaN                       NaN    NaN          NaN
...              ...                       ...    ...          ...
16105            NaN                     8.110  0.000          NaN
16106            NaN                    24.800  0.000          NaN
16107            NaN                   -30.018  0.000          NaN
16108            NaN                    17.584  0.000          NaN
16109            NaN                   -70.556  0.000          NaN
16110            NaN                    29.408  0.000          NaN
16111            NaN                   -35.084  0.000          NaN
16112            NaN                    44.437  0.000          NaN
16113            NaN                       NaN    NaN          NaN
16114            NaN                    54.025  0.000          NaN
16115            NaN                   -29.980  0.000          NaN
16116            NaN                    20.170  0.000          NaN
16117            NaN                       NaN    NaN          NaN
16118            NaN                    36.513  0.000          NaN
16119            NaN                    43.363  0.000          NaN
16120            NaN                    46.667  0.000          NaN
16121            NaN                       NaN    NaN          NaN
16122            NaN                    91.128  0.000          NaN
16123            NaN                    36.894  0.000          NaN
16124            NaN                   -82.064  0.000          NaN
16125            NaN                    28.045  0.000          NaN
16126            NaN                    71.078  0.000          NaN
16127            NaN                   -70.542  0.000          NaN
16128            NaN                    42.922  0.000          NaN
16129            NaN                    30.524  0.000          NaN
16130            NaN                       NaN    NaN          NaN
16131            NaN                    21.141  0.000          NaN
16132            NaN                    36.291  0.000          NaN
16133            NaN                   -41.927  0.000          NaN
16134            NaN                       NaN    NaN          NaN

       revenue_growth    roa    roe    tic  working_capital_ratio
36102             NaN  0.022  0.067  GAS.2                  0.954
36103           1.344  0.011  0.031  GAS.2                  0.877
36104           0.561  0.005  0.016  GAS.2                  0.913
36105          -0.628  0.018  0.058  GAS.2                  0.972
36106          -0.280  0.023  0.067  GAS.2                  1.012
36107           1.761  0.008  0.022  GAS.2                  0.805
36108           0.357  0.004  0.012  GAS.2                  0.867
36109          -0.633  0.016  0.053  GAS.2                  0.845
36110          -0.171  0.019  0.057  GAS.2                  0.644
36111           1.306  0.009  0.025  GAS.2                  0.522
36112           0.426  0.005  0.017  GAS.2                  0.640
36113          -0.698  0.017  0.055  GAS.2                  0.762
36114          -0.157  0.022  0.065  GAS.2                  0.847
36115           1.419  0.008  0.023  GAS.2                  1.043
36116           0.499  0.004  0.013  GAS.2                  0.838
36117          -0.655  0.017  0.053  GAS.2                  0.871
36118          -0.311  0.025  0.071  GAS.2                  0.879
36119           1.917  0.008  0.023  GAS.2                  0.655
36120           0.611  0.004  0.011  GAS.2                  0.656
36121          -0.580  0.016  0.051  GAS.2                  0.696
36122          -0.351  0.019  0.059  GAS.2                  0.625
36123           1.470  0.008  0.025  GAS.2                  0.485
36124           0.572  0.003  0.009  GAS.2                  0.449
36125          -0.663  0.016  0.052  GAS.2                  0.623
36126          -0.335  0.020  0.064  GAS.2                  0.676
36127           1.083  0.019  0.055  GAS.2                  0.602
36128           0.527  0.007  0.021  GAS.2                  0.737
36129          -0.628  0.014  0.048  GAS.2                  0.819
36130          -0.341  0.018  0.055  GAS.2                  0.804
36131           1.963  0.013  0.039  GAS.2                  0.807
...               ...    ...    ...    ...                    ...
16105           0.251  0.042  0.145      D                  1.124
16106          -0.156  0.014  0.048      D                  1.217
16107           0.054  0.007  0.025      D                  0.935
16108          -0.060  0.011  0.040      D                  1.096
16109           0.211  0.008  0.029      D                  0.900
16110          -0.122  0.009  0.034      D                  0.958
16111           0.197  0.004  0.018      D                  0.780
16112          -0.079  0.011  0.041      D                  0.754
16113           0.130  0.006  0.022      D                  0.692
16114          -0.098  0.004  0.018      D                  0.709
16115           0.074 -0.014 -0.062      D                  0.662
16116          -0.120  0.011  0.046      D                  0.738
16117           0.182  0.004  0.018      D                  0.795
16118          -0.132  0.012  0.051      D                  0.807
16119           0.078  0.009  0.037      D                  0.849
16120          -0.123  0.007  0.032      D                  0.863
16121           0.290  0.003  0.014      D                  0.768
16122          -0.078  0.010  0.046      D                  0.719
16123           0.036  0.004  0.021      D                  0.780
16124          -0.137  0.010  0.045      D                  0.630
16125           0.241  0.007  0.033      D                  0.661
16126          -0.075  0.010  0.047      D                  0.611
16127           0.162  0.006  0.028      D                  0.516
16128          -0.125  0.009  0.041      D                  0.494
16129           0.124  0.007  0.032      D                  0.570
16130          -0.170  0.010  0.046      D                  0.421
16131           0.015  0.006  0.031      D                  0.523